server {
    listen 80;
    index index.php;
    root /var/www/public;

    # Разрешаем загрузку файлов до 20МБ (аватарки)
    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass fb_app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Настройки буферов для тяжелых страниц админки
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}